"""add_telegram_file_id_to_meals

Revision ID: 98f35473642f
Revises: 230e151ff858
Create Date: 2026-03-30 12:26:14.207408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f35473642f'
down_revision: Union[str, Sequence[str], None] = '230e151ff858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('telegram_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'telegram_file_id')
    # ### end Alembic commands ###
